### ISSUE TITLE
Get and show available updates for each API

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard#105]
|Part of Epic|
|---|
|#84|
## Description
The wazuh-check-updates plugin should expose a table with information about the status of updates for each API.
Additionally, the check for updates button must perform verification for each API.

## Tasks
- [x] **[wazuh-check-updates Backend]** Expose an endpoint to query the new updates and their details **for each API**. The endpoint should consult the Wazuh API. **Initially the response from the Wazuh API will be mocked**
- [x] **[wazuh-check-updates Backend]** Manage saved objects to save available updates **for each API**.
- [x] **[wazuh-check-updates Backend]** Run a cron job to periodically check for available updates **for each API**.
- [x] **[wazuh-check-updates Frontend]** Expose a table to show the update status **for each API** and the details of each available update.
- [x] **[wazuh-check-updates Frontend]** Modify the exposed notification component.
- [x] **[wazuh-check-updates Frontend]** It must use i18n.
- [x] **[wazuh Frontend]** Consume the frontend components in the About page.
- [x] Unit tests for each development

## About page mockup
![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/2ea9509e-d632-4fa7-b783-b62610982740)

## Notification mockup
![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/9f18af39-7eee-4782-8e0f-524bb34e3aa9)
