### ISSUE TITLE
Create new plugin wazuh-core

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard#106]
|Part of Epic|
|---|
|#84|
## Description
We need to develop a **new core plugin** responsible for centralizing functionality for use in other plugins. Currently, we need to perform the following tasks to prevent the wazuh-check-updates plugins from duplicating code.
The goal of this plugin is to start modularizing common behaviors. Initially the code will not be removed from the main plugin, but will be used from other plugins.

## Tasks
- [x] **[Backend]** Expose an Wazuh API handler**
- [x] **[Backend]** Expose a logger service.
- [x] **[Frontend]** Expose a function to format datetime values.
