### ISSUE TITLE
Check for updates when user logins

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard#109]
|Part of Epic|
|---|
|#84|
## Description
We must to delete the cronjob in the backend of the Wazuh Check Updates plugin because the manager already has a cron job to check for new updates and might get confused. On the other hand, every time the user logins it must check for new available updates.
Additionally, we need to move the security factory functionality to the Wazuh Core plugin and integrate it with Wazuh Check Updates plugin.

## Tasks
- [x] **[wazuh-check-updates Backend]** Delete cron job.
- [x] **[wazuh-check-updates Frontend]** Save in the sessionStorage to check if already check for new updates.
- [x] **[wazuh-core Backend]** Add security factory functionality and expose it.
- [x] **[wazuh-check-updates Backend]** Delete security factory functionality and consume from Wazuh Core plugin.
