### ISSUE TITLE
Add check updates features to API table

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard#114]
|Part of Epic|
|---|
|#84|
## Description
Add check updates features to APIs table in Settings -> API. Add two columns to APIs table indicating the current version of the API and the available updates. To display the details of the available updates, a flyout should be implemented.

## Tasks
- [x] **[Frontend Main Plugin]** Add columns "Version" and "Updates status".
- [x] **[Frontend Main Plugin]** Add flyout to show updates details.
- [x] **[Frontend Check Updates]** Expose a function to check updates.
- [x] **[Frontend Check Updates]** Expose a UI component to change user preference about new update notifications.
