### ISSUE TITLE
Wazuh dashboard fork update

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard#117]
## Description

We want to update our `wazuh-dashboard` change-set with the newest changes from the latest releases of Wazuh. Also, we want to be able to generate packages for all the supported tiers, with the new naming schemes and the new artifactory/storage.

We want to generate portable RPM and DEB packages, so all supported Linux distributions share the appropriate package.

We need to generate automated installation and upgrade tests for each supported platform of the generated packages.  

## Functional requirements

- All the generated packages include all components, plugins and configurations required to provide a production-ready deployment.
- All the Wazuh changes to upstream are incorporated by default in all generated packages
- Incorporate all the identified changes to avoid unnecessary custom package generation
- A developer should be able to generate a package from a given set of branches
- A developer should be able to build packages locally
- A developer should be able to generate package types individually (tgz, rpm, deb, docker)
- A developer should be able to generate all packages in one go

## Non-functional requirements

- We maintain the branch structure of Wazuh, renaming the branches when needed to be coherent with the global process
- We will use GitHub actions to automate the package generation and its testing
- Only authorized users should be able to execute the package generation pipelines
- We should use the Wazuh naming convention for development packages
- All processes must be documented in step-by-step guides, easy to follow by anyone within the repository

## implementation restrictions

- We must use upstream tests to ensure our changes do not break upstream features
- We must implement our own installation and upgrade tests for all our supported platforms and operating systems
- We can explore https://github.com/nektos/act to execute GitHub actions locally

## Plan

- [x] https://github.com/wazuh/wazuh-dashboard/issues/118
- [x] https://github.com/wazuh/wazuh-dashboard/issues/119
- [x] https://github.com/wazuh/wazuh-dashboard/issues/120
- [x] https://github.com/wazuh/wazuh-dashboard/issues/132
- [x] https://github.com/wazuh/wazuh-dashboard/issues/140

**Comment by Tostti** [comment]
Closing this issue as all tasks were successfully completed.
