### ISSUE TITLE
Update packages generation tools I 

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-dashboard#119]
# Description
Currently, we can generate packages of Wazuh Dashboard with the Wazuh Dashboard plugin with our tools. 
As we have more than one plugin, we need to update the tools to support all the plugins we have and may have. 

We also need to support the generation of docker images with the same specifications.

# Functional requirements 

- The generated packages must include all the plugins in `wazuh-dashboard-plugins`, even if we add more plugins in the future. 
- A developer should be able to generate a single package of the required type (`.tar.gz`, `.deb`, `.rpm`, `docker image`)
- A developer should be able to generate all the packages at once if needed. 
- All the generated packages should be production-ready, without needing any additional configurations or steps.

# Non-functional requirements 
- All the tools should be properly tested. 
- All the tools should be properly documented. 
- There should be documentation in the repo that anyone can read and follow to generate a package. 

# Plan
- [x] Update the `tar.gz` generating tool
- [x] Update the `deb` generating tool
- [x] Update the `rpm` generating tool
- [x] Generate the proper documentation

**Comment by yenienserrano** [comment]
A problem was encountered when trying to generate the package for the arm64 architecture, the error is:
```
/home/runner/work/wazuh-dashboard/wazuh-dashboard/dev-tools/build-packages/base/tmp/wazuh-dashboard-4.9.0-1-linux-arm64/node/fallback/bin/node: Exec format error
```
