### ISSUE TITLE
Update GitHub Actions I 

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-dashboard#120]
# Description
Currently, we have a GitHub action that can generate packages using our packages-generation tools. 
We need to support generating packages using any version of Wazuh Dashboard and the plugins. 

# Functional requirements

- The actions should be able to run in any of the branches 
- The actions should be able to select any branch of the plugins 
- The generated packages should include all the available plugins for that branch
- A developer should be able to generate all the packages at once
- A developer should be able to generate only one package of the required type
- The actions should only be able to be launched by authorized people

# Non-functional requirements

- The actions should be properly documented
- The actions should be properly tested

# Plan
- [x] Update the current action to support any `wazuh-dashboard-plugins` branch https://github.com/wazuh/wazuh-dashboard-plugins/issues/6194
- [x] Update the action to support any of the `wazuh-dashboard` branches
- [x] Configure and test the repo security for the actions https://github.com/wazuh/wazuh-security-dashboards-plugin/issues/32
