### ISSUE TITLE
Generate testing for packages

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-dashboard#132]
# Description 
We have to generate tools that test the generated packages.

# Functional requirements
- The tests should be done in an action 
- It should install the package in a system
- It should verify that the package can be installed
- It should verify the location, permissions, and owners of the files 
- It should verify the content of the `opensearch_dashboards.yml`
- It should verify the package metadata
- It should be possible to test all the types of package

# Non-functional requirements 
- This needs to be documented, so anyone can easily test a package

# Plan
- [x] Generate a test Action
- [x] Add logic to test rpm packages
- [x] Add logic to test deb packages
