### ISSUE TITLE
Update the repo with the latest changes of Wazuh Dashboard

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-dashboard#140]
# Description
At this time, Wazuh Dashboard is generated with the https://github.com/wazuh/wazuh-packages repository. However, in future releases this repo will be used instead. We need to identify all the new changes in `wazuh-packages` and bring them here, so there are no differences when we generate new packages using this repo. 

# Tasks 

- [x] Identify and list all the changes that are not currently in this repo
- [x] Update the repo with the required changes

**Comment by yenienserrano** [comment]
## Identify and list all the changes that are not currently in this repo

- [ ]  https://github.com/wazuh/wazuh-packages/pull/2615
