### ISSUE TITLE
Wazuh packages redesign tier 1 - Stage 2 -  Migrate and adapt the Wazuh dashboard

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-dashboard#147]
## Description
We are on an effort to modernize the packages' generation and lifecycle. This issue aims to track the effort to migrate the packages' generation process from the wazuh-packages repository and automate its generation, testing and delivery steps of their lifecycle.

The tasks listed below are extracted from https://github.com/wazuh/internal-devel-requests/issues/712. Use that issue for additional information and requirements.

Note that most of these tasks are already part of the https://github.com/wazuh/wazuh-dashboard/issues/117 project. We'll use that one for development and this one for tracking, describing the steps taken for each of them.

## Tasks

- [x] Migrate code into target repository for manual package generation
    - https://github.com/wazuh/wazuh-dashboard/pull/71
    - https://github.com/wazuh/wazuh-dashboard/issues/85
    - https://github.com/wazuh/wazuh-dashboard/issues/119
- [x] Automate packages generation through CI
    - https://github.com/wazuh/wazuh-dashboard/issues/120
- [x] Automate packages testing through CI
    - https://github.com/wazuh/wazuh-dashboard/issues/132
- [x] Add secrets to GH (to upload packages to S3)
- [x] https://github.com/wazuh/wazuh-dashboard/pull/151

**Comment by rauldpm** [comment]
First estimated ETA provided by @Tostti : `2024/03/22`

**Comment by rauldpm** [comment]
The repository has been configured with CI secrets, please, refer to the main comment of the https://github.com/wazuh/wazuh-jenkins/issues/6290 issue to check the secrets names, the CI used has been configured to put and get objects from the development warehouse
