### ISSUE TITLE
Disable the addition of sample data

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-dashboard#19]
## Description

There is a feature in OpenSearch Dashboards which allows the users and adds sample data in order to create a playground on which to create visualizations and explore the features of the platform.

In the future, we'll probably use this feature to add Wazuh's sample data, replacing this same functionality from the plugin, but until then, we need to disable this feature to avoid confusing the users.

There are several places in the app from which this feature can be accessed, so we'll need to study the best approach to disable this feature globally, being the least intrusive as possible in terms of code changes.

## Context

Here's the view:

![image](https://user-images.githubusercontent.com/15186973/217812792-6a3308ec-f840-44df-bae7-d4f84f121247.png)

Route: `app/home#/tutorial_directory`

Places from which this view is reference and/or can be accessed:

1. Home
![image](https://user-images.githubusercontent.com/15186973/217813422-13d3450b-57da-4124-afb0-b6e0828fb5b1.png)
2. Feature directory (link `View app directory` in Home)
![image](https://user-images.githubusercontent.com/15186973/217813927-3a714de4-4720-4698-b115-5e055613cbb5.png)
3. Index pattern (on empty state --> no index patterns)

Additional context: search results for `tutorial_directory`
```
17 results - 12 files

wazuh-dashboard/src/plugins/home/public/plugin.ts:
  143        showOnHomePage: true,
  144:       path: `${HOME_APP_BASE_PATH}#/tutorial_directory`,
  145        category: 'data' as FeatureCatalogueCategory.DATA,

wazuh-dashboard/src/plugins/home/public/application/components/welcome.tsx:
  81    private redirecToAddData() {
  82:     const path = this.services.addBasePath('#/tutorial_directory');
  83      window.location.href = path;

wazuh-dashboard/src/plugins/index_pattern_management/public/components/index_pattern_table/empty_state/empty_state.tsx:
  157                  className="inpEmptyState__card"
  158:                 onClick={() => navigateToApp('home', { path: '#/tutorial_directory' })}
  159                  icon={<EuiIcon size="xl" type="database" color="subdued" />}

  177                  className="inpEmptyState__card"
  178:                 onClick={() => navigateToApp('home', { path: '#/tutorial_directory/sampleData' })}
  179                  icon={<EuiIcon size="xl" type="heatmap" color="subdued" />}

wazuh-dashboard/src/plugins/opensearch_dashboards_react/public/overview_page/overview_page_header/overview_page_header.tsx:
  166                        flush="both"
  167:                       href={addBasePath('/app/home#/tutorial_directory')}
  168                        iconType="indexOpen"

wazuh-dashboard/test/accessibility/apps/dashboard_panel.ts:
  40      before(async () => {
  41:       await PageObjects.common.navigateToUrl('home', '/tutorial_directory/sampleData', {
  42          useActualUrl: true,

wazuh-dashboard/test/accessibility/apps/dashboard.ts:
  44      before(async () => {
  45:       await PageObjects.common.navigateToUrl('home', '/tutorial_directory/sampleData', {
  46          useActualUrl: true,

wazuh-dashboard/test/accessibility/apps/filter_panel.ts:
  41      before(async () => {
  42:       await PageObjects.common.navigateToUrl('home', '/tutorial_directory/sampleData', {
  43          useActualUrl: true,

wazuh-dashboard/test/accessibility/apps/home.ts:
  46      it('Add OpenSearch Dashboards sample data page', async () => {
  47:       await PageObjects.common.navigateToUrl('home', '/tutorial_directory/sampleData', {
  48          useActualUrl: true,

wazuh-dashboard/test/accessibility/apps/opensearch_dashboards_overview.ts:
  45      after(async () => {
  46:       await PageObjects.common.navigateToUrl('home', '/tutorial_directory/sampleData', {
  47          useActualUrl: true,

  57      it('Overview view', async () => {
  58:       await PageObjects.common.navigateToUrl('home', '/tutorial_directory/sampleData', {
  59          useActualUrl: true,

wazuh-dashboard/test/functional/apps/home/_add_data.ts:
  39      it('directory should not display registered tutorials', async () => {
  40:       await PageObjects.common.navigateToUrl('home', 'tutorial_directory', { useActualUrl: true });
  41        await PageObjects.header.waitUntilLoadingHasFinished();

wazuh-dashboard/test/functional/apps/home/_sample_data.ts:
   50        ]);
   51:       await PageObjects.common.navigateToUrl('home', '/tutorial_directory/sampleData', {
   52          useActualUrl: true,

  101        beforeEach(async () => {
  102:         await PageObjects.common.navigateToUrl('home', '/tutorial_directory/sampleData', {
  103            useActualUrl: true,

  166        beforeEach(async () => {
  167:         await PageObjects.common.navigateToUrl('home', '/tutorial_directory/sampleData', {
  168            useActualUrl: true,

wazuh-dashboard/test/functional/page_objects/common_page.ts:
  135       * @param appName As defined in the apps config, e.g. 'home'
  136:      * @param subUrl The route after the hash (#), e.g. '/tutorial_directory/sampleData'
  137       * @param args additional arguments

  173       * @param appName As defined in the apps config, e.g. 'home'
  174:      * @param subUrl The route after the appUrl, e.g. '/tutorial_directory/sampleData'
  175       * @param args additional arguments
```

## Tasks

In particular, we'll need to:

- [x] Hide the component `Add sample data`, present in several views
![image](https://user-images.githubusercontent.com/15186973/217814375-ec08cd60-f93d-4ed1-9fc1-fcfbdbdf9d25.png)
- [x] Adjust the parent views as necessary.
- [x] Disable some or all of the links listed above.

**Comment by AlexRuiz7** [comment]
@yenienserrano I found a new way to add sample data: the first time the app is accessed, this component shows up.

![Screenshot from 2023-03-22 20-01-55](https://user-images.githubusercontent.com/15186973/227014173-c5052453-d00d-4a57-8313-bce306f711d5.png)

**Comment by yenienserrano** [comment]
For this sign to appear in the local storage, the property `home:welcome:show` does not have to be present.

**Comment by AlexRuiz7** [comment]
No proposed solution?
