### ISSUE TITLE
Custom branding (II)

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard#20]
We want to be able to customize some parts of the dashboard experience, so our community can tailor the experience for their users.

- [ ] Remove Wazuh wording from the health check page

<img width="395" alt="image" src="https://user-images.githubusercontent.com/2181918/217773426-c3ba9074-d069-4077-aab3-c399764da145.png">

- [ ] Remove duplicated help entries

<img width="224" alt="image" src="https://user-images.githubusercontent.com/2181918/217773802-f83c6b46-ab1f-490c-88de-5702cd3b15f4.png">

- [ ] Customize icons / text on the left menu

<img width="312" alt="image" src="https://user-images.githubusercontent.com/2181918/217775871-67dccd61-115a-41dd-a682-b88fd8263c01.png">

- [ ] Customize logo and color in the login screen

<img width="582" alt="image" src="https://user-images.githubusercontent.com/2181918/217776264-ec140745-7f1d-4181-8b01-bebc69ca4a46.png">

- [ ] Customize loading page logo

<img width="407" alt="image" src="https://user-images.githubusercontent.com/2181918/217777008-813f0a1f-1979-4221-af98-58a118a073cb.png">

We need to this to be configurable in our configuration files and from the user interface / API.
Also, we should explore CSS options enabling the interface to update dynamically.

We must consider the work being done already in opensearch:

https://github.com/opensearch-project/OpenSearch-Dashboards/issues?q=is:issue+is:open+branding

If our solution could benefit all opensearch community, we should open a PR in their repository, and try to incorporate the changes into the upstream.

**Comment by gdiazlo** [comment]
This has been superseded by already merged issues.
