### ISSUE TITLE
Support new stage Alpha 1 for 4.9.0 in wazuh-dashboard repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-dashboard#203]
## Description

This issue attempts to support a new stage Alpha 1 for 4.9.0 in the wazuh-dashboard repository.

## Tasks

- [ ] Ensure changelog is updated for 4.9.0 (if applicable).
- [ ] Bump revision for branch 4.9.0 on wazuh-dashboard repository.
- [ ] Create tag v4.9.0-alpha1 from branch 4.9.0 on wazuh-dashboard repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard/releases/tag/v4.9.0-alpha1.
