### ISSUE TITLE
Spike - agent comms API UX

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard#209]
# Description
The goal of this epic is to design a user interface for the new agent comms API. We must provide a UI that allows the user to handle agent management and configure the agent comms settings.

As part of the design, we want to relocate the apps in the main global menu. For example, like in the following proposal: 

```
# Security operations
## IT hygiene (Endpoints inventory)

# Fleet
## Agents summary
## Agents groups
## Agent commands
## Comms configuration

# Security policies
## Policies
## Rules (and Ruleset test)
## Decoders
## KVDBs
## Engine settings

# Reporting
## Report scheduler

# Observability
## Notebooks (Agent and engine metrics)

# Server management
## Endpoints summary [remove]
## Endpoints groups [remove]
## Rules [remove]
## Decoders [remove]
## CDB List [remove]
## Settings [remove]
## Ruleset test [remove]
```

## Functional Requirements
- **Fleet management**: Provide a user interface to handle all possible operations with Wazuh agents: Register, upgrade, and delete agents. Also, it should provide features to handle the group's assignment for the agents (add to a group, remove from a group).
- **Agent comms API configuration**: Provide a user interface to configure the agent comms settings.

## Implementation Restrictions
- The features mentioned above must be implemented as a separate, single plugin.
- The plugin must use I18n for all the UI texts, so they can be translated to other languages.
- The UI must be responsive for different viewport sizes
- The features of the plugin must be able to be restricted by the user role (RBAC). Define roles by default.
- Fleet management use cases must use the Server API (55000 port) endpoints instead of the Indexer API (9200) endpoints.

## Plan
- [x] Create a new plugin
- **Fleet management**
  - [x] Create side menú
  - [x] Create a basic layout to have a draft of how it would look with simple interactions
  - [x] Create mocked data in an index with basic fields
  - [x] The mocked data should be WCS (Wazuh Common Schema) compliant
  - [x] Analyze visualizations and insights that may add value to the user experience.
- **Agent API configuration**
  - [ ] Create a basic layout to have a draft of how it would look with simple interactions
  - [ ] Create mocked data in the imposter to handle the requests
  - [ ] Explore the possibility of updating only the configuration that changes instead of sending a request that updates all of them

**Comment by lucianogorza** [comment]
# General

## Create new plugin `wazuh-fleet`

![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/05bbb25d-60b4-409a-a54c-283097e03e8d)

**Comment by lucianogorza** [comment]
# Fleet management

## Create side menú component and implement from the main plugin

![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/8f242165-7001-4743-89c3-ed37e05d4056)

**Comment by lucianogorza** [comment]
# Update 28/06/2024

## Inject data and create `wazuh-fleet-agents-*` index pattern

![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/cab0add0-70aa-4ded-b7a7-534d5d12a7e7)

**Comment by Machi3mfl** [comment]
## Tasks

- [ ] Add visualizations in the Agents Summary section. Top agents, top groups (In progress ⏳)

**Comment by lucianogorza** [comment]
# Update 03/07/2024

## Add global actions to layout and integrate visualizations

![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/4290f411-b599-4a67-b25b-0bebb46470d2)

**Comment by Machi3mfl** [comment]
## Update 04/07/2024

## Add groups section

### Tasks

- [ ] Create new groups index pattern (In progress ⏳)
- [ ] Add table with search bar (reuse the agent's table and components) (In progress ⏳)

**Comment by lucianogorza** [comment]
# Update 04/07/2024

## Add mocked global actions and styles to columns

![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/f7e43853-162c-462a-8923-17f715788122)

**Comment by lucianogorza** [comment]
# Update 05/07/2024

## Add agent details flyout and page

### Agent page

![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/df2b2e5c-032c-41f7-afa1-bbaefa2451cf)

### Agent flyout

![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/115693fc-3ad2-479a-ab56-f4ce273ee0d9)

[screen-capture.webm](https://github.com/wazuh/wazuh-dashboard/assets/103193307/d587ae3e-2ded-41d1-8da4-c5efcb5a760d)

## Add routing to agent details

![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/15a6800a-7544-4d67-9762-449c73bcceb0)

**Comment by Machi3mfl** [comment]
# Update 10/07/2024

## Add actions and links to the Groups Table

<img width="1512" alt="Screenshot 2024-07-10 at 13 26 58" src="https://github.com/wazuh/wazuh-dashboard/assets/6089438/a34d566e-8f5d-413f-acda-bd9804b2f0c1">

<img width="1512" alt="Screenshot 2024-07-10 at 13 27 16" src="https://github.com/wazuh/wazuh-dashboard/assets/6089438/e5f38786-c57f-4842-af58-4b9892de1e92">

## Add groups resume flyout

<img width="1512" alt="Screenshot 2024-07-10 at 13 27 35" src="https://github.com/wazuh/wazuh-dashboard/assets/6089438/90605489-bd50-4f70-9912-956404264d05">

## Add groups table cell link to group details route

https://github.com/wazuh/wazuh-dashboard/assets/6089438/444b3a5e-48cb-4d86-a493-2a9b5ab6ca82

**Comment by Machi3mfl** [comment]
## Update 12/07/2024

- [ ] Use the wazuh-indexer script to generate index templates 

**Adjustments to run script in macOS**

<img width="877" alt="Screenshot 2024-07-15 at 08 39 05" src="https://github.com/user-attachments/assets/cf71058d-dbe7-40bc-9aac-6653c8bd9ec4">

1. `sed error`
  - Solved adding params to the sed command
<img width="1341" alt="Screenshot 2024-07-15 at 08 51 43" src="https://github.com/user-attachments/assets/023ea314-9382-4b49-b14d-dcfebb73ae63">

2. `jq: command not found`

```
   brew install jq
```

After 

<img width="872" alt="Screenshot 2024-07-15 at 08 53 13" src="https://github.com/user-attachments/assets/9e9f0ffd-1003-4b74-a2a0-b3b1036ef655">

<img width="344" alt="Screenshot 2024-07-15 at 08 54 03" src="https://github.com/user-attachments/assets/76e6ef7a-636b-4ef6-b56e-cfd246356c46">

- [ ] Adjust event_generator to agent index
- [ ] Create inventory template and events generator script

**Comment by Machi3mfl** [comment]
# Creating command index template (02/08/2024)

### Installing dependencies

![Screenshot 2024-08-02 at 16 25 29](https://github.com/user-attachments/assets/dbdb9f00-3ac9-4e83-8645-161df6ce853d)

### Fixing indentation and exceeded description on the args field

![Screenshot 2024-08-02 at 16 04 34](https://github.com/user-attachments/assets/d265f09e-9564-42e3-bf0a-bd0b4063cfbf)

### Created commands template successfully

![Screenshot 2024-08-02 at 16 10 55](https://github.com/user-attachments/assets/2ee85331-3fee-42f0-835e-b926a9525e2e)

> [!WARNING]
> Error adding template using OSD Dev Tools. The 

<img width="1512" alt="Screenshot 2024-08-02 at 16 23 11" src="https://github.com/user-attachments/assets/0560b84b-d28a-4bde-85b0-2e3751c5410e">

> [!NOTE]
> Fixed changing the type wildcard to text


<img width="1510" alt="Screenshot 2024-08-02 at 16 49 51" src="https://github.com/user-attachments/assets/01b7fd10-9cb7-4882-8ee1-375305743c92">

**Comment by lucianogorza** [comment]
## Update 05/08/2024

### Agent details dashboard

![image](https://github.com/user-attachments/assets/5c4f1e57-6981-43b5-a6ae-f23edb6a646c)

**Comment by lucianogorza** [comment]
## Update 06/08/2024

### Add navigate button

![image](https://github.com/user-attachments/assets/ba8107c0-63e0-4803-9817-c1da608855ef)
