### ISSUE TITLE
POC engine UX - security policy management

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard#216]
## Description
We have to create a new proof of concept plugin that allows the user to manage the new engine. 

The engine has the following object types:
- policies (a list of integrations)
- decoders
- rules
- outputs
- filters
- integrations ( a set of decoders, rules, filters, and outputs)
- kvdbs

Related to the security policy management the engine defines:
- routes
- endpoint to test events against a policy

These concepts are defined in the [engine user manual](https://docs.google.com/document/d/1N0p7pd7XszQwFU9HBjpB7txIw2DCcAsV-BKfEZSLixw/edit)

Based on this, we need to propose a UI to manage these concepts.

We need to provide an intuitive interface for the engine configuration changes, allowing users to easily adjust settings.
It should list the engine configuration and provide a form to edit each setting, ideally using different controls for different configuration data types, validanting the user input.

Also, we need to provide a way to manage KVDBs which is the replacement of the current CDBs. The main difference is that KVDBs are dynamic and can be updated while the policy is running. KVDBs will not be stored in the indexer, so these operations should assume it will be accessed using the API.

### References
- Create plugin: https://opensearch.org/blog/dashboards-plugins-intro/
- Index mocked data: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/docs-index_.html
- Vega examples: https://vega.github.io/vega/examples/
- Vega docs: https://opensearch.org/docs/latest/dashboards/visualize/vega/
- Vega (Kibana 7.10): https://www.elastic.co/guide/en/kibana/7.10/vega-reference.html

## Plan

- [ ] Create a new plugin with a basic layout to have a draft of how it would look with simple interactions
- [ ] Create mocked data in indexes with basic fields
- [ ] The mocked data should be WCS (Wazuh Common Schema) compliant
- [ ] Analyse the possibility of using a Vega visualisation to display rules relationships
- [ ] Mock API endpoints to be able to have a minimum interaction with the UI

**Comment by Desvelao** [comment]
Reserved

**Comment by Desvelao** [comment]
Reserved

**Comment by Desvelao** [comment]
# Research - Rule relationship visualization

I was exploring the idea to represent the rule relationships through a Vega visualization.

I don't know what is the final document schema of a rule definition, but I defined a simple schema to test the representation of rule relationship storing in the rules data:
- id: rule ID
- parent: parent ID

Reviewing the chart types, I decided to test with the [Tree layout](https://vega.github.io/vega/examples/tree-layout/).

> :information_source: From my tests, the `Tree layout` chart needs only one root of the data to build the tree. It could not get to work with multiple tree roots. So this could mean one restriction depending on the use case.

<details>
  <summary>Following this approach I store some data on an index on Wazuh indexer</summary>
  
  I created an index where I store some mocked documents related to rules.

```
PUT /wazuh-rules
{
  "settings": {
    "number_of_shards": 1,
    "number_of_replicas": 0
  },
  "mappings": {
    "properties": {
      "id": { "type": "keyword" },
      "parent": { "type": "keyword" }
    }
  }
}
```

Then I indexed some documents:

```
POST /wazuh-rules/_doc
{
  "id": "1"
}

POST /wazuh-rules/_doc
{
  "id": "2",
  "parent": "1"
}

POST /wazuh-rules/_doc
{
  "id": "3",
  "parent": "1"
}

POST /wazuh-rules/_doc
{
  "id": "4"
}
```
</details>

With the data rule on the Wazuh indexer, I created a visualization of `Vega` type.

<details>
  <summary>Vega visualization definition</summary>
  
> The visualization has hard-coded the values of the index to search and the `id` or `parent` document to get.
> The data is retrieved using a `query` and use the `hits`. It is possible to use aggregations, but it could not make sense for the use case.
> The visualization has defined some controls to modify the behavior and representation. These were inhitated from the example visualization of `Tree Layout` example. We could remove them.
> The visualization only displays a node and its children on the first level. Using a less-restricted query could display more depth, but depending on the data could cause the tree have multiples nodes and this gives an error.
  
  ```
  {
  $schema: https://vega.github.io/schema/vega/v5.json
  description: An example of Cartesian layouts for a node-link diagram of hierarchical data.
  padding: 5
  signals: [
    {
      name: labels
      value: true
      bind: {
        input: checkbox
      }
    }
    {
      name: layout
      value: tidy
      bind: {
        input: radio
        options: [
          tidy
          cluster
        ]
      }
    }
    {
      name: links
      value: diagonal
      bind: {
        input: select
        options: [
          line
          curve
          diagonal
          orthogonal
        ]
      }
    }
    {
      name: separation
      value: false
      bind: {
        input: checkbox
      }
    }
  ]
  data: [
    {
      name: tree
      url: {
      /*
      An object instead of a string for the "url" param is treated as an OpenSearch query. Anything inside this object is not part of the Vega language, but only understood by OpenSearch Dashboards and OpenSearch server. This query counts the number of documents per time interval, assuming you have a @timestamp field in your data.

      OpenSearch Dashboards has a special handling for the fields surrounded by "%".  They are processed before the the query is sent to OpenSearch. This way the query becomes context aware, and can use the time range and the dashboard filters.
      */

      // Apply dashboard context filters when set
      // %context%: true
      // Filter the time picker (upper right corner) with this field
      // %timefield%: @timestamp

      /*
      See .search() documentation for :  https://opensearch.org/docs/latest/clients/javascript/
      */

      // Which index to search
        index: wazuh-rules


      // If "data_source.enabled: true", optionally set the data source name to query from (omit field if querying from local cluster)
      // data_source_name: Example US Cluster

      // Aggregate data by the time field into time buckets, counting the number of documents in each bucket.
        body: {
          query: {
            bool: {
              should: [
                {
                  match_phrase: {
                    id: 1
                  }
                }
                {
                  match_phrase: {
                    parent: 1
                  }
                }
              ]
              minimum_should_match: 1
            }
          }
          /* query: {
            match_all: {
            }
          } */
          size: 1000
        }
      }
    /*
    }

    For our graph, we only need the list of bucket values.  Use the format.property to discard everything else.
    */
      format: {
        property: hits.hits
      }
      transform: [
        {
          type: stratify
          key: _source.id
          parentKey: _source.parent
        }
        {
          type: tree
          method: {
            signal: layout
          }
          size: [
            {
              signal: height
            }
            {
              signal: width - 100
            }
          ]
          separation: {
            signal: separation
          }
          as: [
            y
            x
            depth
            children
          ]
        }
      ]
    }
    {
      name: links
      source: tree
      transform: [
        {
          type: treelinks
        }
        {
          type: linkpath
          orient: horizontal
          shape: {
            signal: links
          }
        }
      ]
    }
  ]
  scales: [
    {
      name: color
      type: linear
      range: {
        scheme: magma
      }
      domain: {
        data: tree
        field: depth
      }
      zero: true
    }
  ]
  marks: [
    {
      type: path
      from: {
        data: links
      }
      encode: {
        update: {
          path: {
            field: path
          }
          stroke: {
            value: "#ccc"
          }
        }
      }
    }
    {
      type: symbol
      from: {
        data: tree
      }
      encode: {
        enter: {
          size: {
            value: 100
          }
          stroke: {
            value: "#fff"
          }
        }
        update: {
          x: {
            field: x
          }
          y: {
            field: y
          }
          fill: {
            scale: color
            field: depth
          }
        }
      }
    }
    {
      type: text
      from: {
        data: tree
      }
      encode: {
        enter: {
          text: {
            field: _source.id
          }
          fontSize: {
            value: 15
          }
          baseline: {
            value: middle
          }
        }
        update: {
          x: {
            field: x
          }
          y: {
            field: y
          }
          dx: {
            signal: datum.children ? -7 : 7
          }
          align: {
            signal: datum.children ? 'right' : 'left'
          }
          opacity: {
            signal: labels ? 1 : 0
          }
        }
      }
    }
  ]
}
  ```
</details>

![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/dab3a143-4e8f-4075-9c8c-c6a3d287b72a)

Then, I got the visualization definition and used the same mechanism to render a dashboard used on the main plugin, and I got the visualization:
![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/4caf1054-49cc-4040-8734-466843b96683)

**Comment by JuanGarriuz** [comment]
Mocked API response and flyout added


https://github.com/wazuh/wazuh-dashboard/assets/124377319/f1d1352d-5df2-4d30-a9cc-a483c98ae471

**Comment by Desvelao** [comment]
# POC - Rules

This section has the following capabilities:

- List rules
![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/ccde86fd-a1d3-4afa-9ee7-bcfc8e77bf0b)
  - Export to CSV
  
- Rule details
  - Table
![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/6b9ad9f6-58fb-4848-88b7-cf5184d63983)
    - JSON
![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/b7580d54-3d01-4ae9-81e6-90d35c1ace3b)
   - Relationship with other rules
![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/dd7988d2-b525-4111-b426-6c4ced3be1b9)
   - Events
![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/645e3b02-75f9-4130-a249-6def80f7b9b4)

- Create rule
![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/9dd0287a-d4ad-48a7-8186-bd8bda4f11ad)
![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/f6c13519-f6bd-49c6-ac2a-78f2cd23543f)

- Import from file

**Comment by JuanGarriuz** [comment]
### Update KVDB 10/07

- Added a new custom button to render flyout.

![image](https://github.com/wazuh/wazuh-dashboard/assets/124377319/38258de7-d1be-45f4-b208-5e4dc71a2cf3)
![image](https://github.com/wazuh/wazuh-dashboard/assets/124377319/33eabbce-f58d-4559-b180-f02343b59e8a)

- Added custom action buttons and functionality with API

![image](https://github.com/wazuh/wazuh-dashboard/assets/124377319/2fc48a49-9e06-4234-b863-77e463b4983f)

- Added Routing with react

#### ToDo

- [ ] Refactor flyout
- [ ] Add table buttons funcionality

**Comment by JuanGarriuz** [comment]
### Update 15/07

![image](https://github.com/user-attachments/assets/1eb0497b-2c7e-464c-b00e-62fd658f7cef)
![image](https://github.com/user-attachments/assets/08e6060d-3658-40d3-bba5-1a8f0ee790d3)


ToDo

- [ ] Upgrade flyout styles
- [ ] Add a sample data script
- [ ] Add functional actions buttons

**Comment by JuanGarriuz** [comment]
### Update 02/08

**Comment by Desvelao** [comment]
POC - Outputs

- List
![image](https://github.com/user-attachments/assets/23d0f03f-fa95-4bc0-93e5-2af0b42ca39b)
![image](https://github.com/user-attachments/assets/30c1a41f-a6c0-4ceb-bc75-177fa37d7290)
![image](https://github.com/user-attachments/assets/e51bf15c-75f0-4716-8ec5-996ef314cff8)

- Bulk actions
![image](https://github.com/user-attachments/assets/477eabb9-169e-4fb7-b2b7-46cafcc5cc4d)

- Details

  - Table
![image](https://github.com/user-attachments/assets/de9edaf3-5d9e-435b-ada6-68a4b668484d)

 - JSON
![image](https://github.com/user-attachments/assets/5a59d24e-d0f9-46a6-8f0e-77863db10476)

- File
![image](https://github.com/user-attachments/assets/cd087611-fcad-41ae-95ce-f2ae9819eca1)

- Relationship
TODO

- Events
![image](https://github.com/user-attachments/assets/e33cb3e3-b156-4265-91cd-1e7f4d5bff14)

- Create
![image](https://github.com/user-attachments/assets/58b2083b-d383-473b-95cd-91eed8722a29)
Form: TBD
File: 
![image](https://github.com/user-attachments/assets/98b00d5f-664d-49f6-877d-fd11fddc69c9)
