### ISSUE TITLE
POC agent comms UX - fleet management

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard#220]
# Description
We have to create a new proof of concept plugin that is able to manage the fleet of agents. This plugin must be able to list, register, upgrade, and delete agents. Also, it should provide features to handle the group's assignment for the agents (add to a group, remove from a group).
 

## Tasks

- [ ] Create a new plugin with a basic layout to have a draft of how it would look with simple interactions
- [ ] Create mocked data in an index with basic fields
- [ ] The mocked data should be WCS (Wazuh Common Schema) compliant
- [ ] Analyze visualizations and insights that may add value to the user experience.

**Comment by lucianogorza** [comment]
The issue is part of then POC in https://github.com/wazuh/wazuh-dashboard/issues/209
