### ISSUE TITLE
POC agent comms UX - agent comms API configuration

### ISSUE THREAD

**Issue by asteriscos** [wazuh/wazuh-dashboard#221]
# Description
We have to create a new proof of concept plugin that is able to manage agent comms settings. This plugin must be able to list or edit current configurations using web forms.

## Tasks

- [ ] Create a new plugin with a basic layout to have a draft of how it would look with simple interactions
- [ ] Create mocked data in the imposter to handle the requests
- [ ] Explore the possibility of updating only the configuration that changes instead of sending a request that updates all of them

**Comment by lucianogorza** [comment]
The issue is part of then POC in https://github.com/wazuh/wazuh-dashboard/issues/209
