### ISSUE TITLE
Support new stage Alpha 2 for 4.9.0 in wazuh-dashboard repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard#235]
## Description

This issue attempts to support a new stage Alpha 2 for 4.9.0 in the wazuh-dashboard repository.

## Tasks

- [x] Ensure changelog is updated for 4.9.0 (if applicable).
- [x] Bump revision for branch 4.9.0 on wazuh-dashboard repository. https://github.com/wazuh/wazuh-dashboard/pull/236 https://github.com/wazuh/wazuh-dashboard/pull/237
- [x] Create tag v4.9.0-alpha2 from branch 4.9.0 on wazuh-dashboard repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard/releases/tag/v4.9.0-alpha2.
