### ISSUE TITLE
Support new stage RC 3 for 4.8.1 in wazuh-dashboard repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard#240]
## Description

This issue attempts to support a new stage RC 3 for 4.8.1 in the wazuh-dashboard repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.1 (if applicable).
- [ ] Bump revision for branch 4.8.1 on wazuh-dashboard repository.
- [ ] Create tag v4.8.1-rc3 from branch 4.8.1 on wazuh-dashboard repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard/releases/tag/v4.8.1-rc3.

**Comment by Tostti** [comment]
The repository is not used in versions lower than 4.9.0. I will close this issue
