### ISSUE TITLE
Support new stage RC 4 for 4.8.1 in wazuh-dashboard repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard#246]
## Description

This issue attempts to support a new stage RC 4 for 4.8.1 in the wazuh-dashboard repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.1 (if applicable).
- [ ] Bump revision for branch 4.8.1 on wazuh-dashboard repository.
- [ ] Create tag v4.8.1-rc4 from branch 4.8.1 on wazuh-dashboard repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard/releases/tag/v4.8.1-rc4.
