### ISSUE TITLE
Support new stage Alpha 3 for 4.9.0 in wazuh-dashboard repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard#251]
## Description

This issue attempts to support a new stage Alpha 3 for 4.9.0 in the wazuh-dashboard repository.

## Tasks

- [x] Ensure changelog is updated for 4.9.0 (if applicable).
- [x] https://github.com/wazuh/wazuh-dashboard/pull/252
- [x] Create tag v4.9.0-alpha3 from branch 4.9.0 on wazuh-dashboard repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard/releases/tag/v4.9.0-alpha3.

**Comment by chantal-kelm** [comment]
LGTM
