### ISSUE TITLE
Support new stage RC 1 for 4.8.2 in wazuh-dashboard repository

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-dashboard#270]
## Description

This issue attempts to support a new stage RC 1 for 4.8.2 in the wazuh-dashboard repository.

## Tasks

- [ ] Ensure changelog is updated for 4.8.2 (if applicable).
- [ ] Bump revision for branch 4.8.2 on wazuh-dashboard repository.
- [ ] Create tag v4.8.2-rc1 from branch 4.8.2 on wazuh-dashboard repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard/releases/tag/v4.8.2-rc1.

**Comment by Tostti** [comment]
The repository is not used in versions lower than 4.9.0. I will close this issue
