### ISSUE TITLE
Generate final tag and publish draft release for Wazuh 4.9.0-2

### ISSUE THREAD

**Issue by Tostti** [wazuh/wazuh-dashboard#297]
## Description

This issue attempts to publish draft release and generate final tag for version 4.9.0 in the wazuh-dashboard repository.

## Tasks

- [x] Modify the workflow to use the new tag
    - https://github.com/wazuh/wazuh-dashboard/pull/298
- [x] Generate final tag v4.9.0 from branch 4.9.0 on wazuh-dashboard repository.
- [x] Publish [GitHub draft release](https://github.com/wazuh/wazuh-dashboard/releases) from [tag v4.9.0-2]
