### ISSUE TITLE
Support new stage RC 1 for 4.9.1 in wazuh-dashboard repository

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-dashboard#317]
## Description

This issue attempts to support a new stage RC 1 for 4.9.1 in the wazuh-dashboard repository.

## Tasks

- [x] Ensure changelog is updated for 4.9.1 (if applicable).
- [x] Bump revision for branch 4.9.1 on wazuh-dashboard repository.
  -  https://github.com/wazuh/wazuh-dashboard/pull/318 
  - https://github.com/wazuh/wazuh-dashboard/pull/319
- [x] Create tag v4.9.1-rc1 from branch 4.9.1 on wazuh-dashboard repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard/releases/tag/v4.9.1-rc1.

**Comment by Desvelao** [comment]
LGTM!
