### ISSUE TITLE
Skip/fix failing Cypress tests

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-dashboard#34]
## Description

Related issue: #32 

As we do not have a fork repository of [tests repo][tests-repo], we need to skip the Cypress tests that are failing due to our changes, at least until we find a better solution.

### Tasks

- [x] Detect the tests that fail.
- [x] Detect tests that fail because of our changes. If so, skip them.
- [x] For the tests that fail for other reason, find a way to solve them.

We expected all the tests from the Cypress tests suite to pass.

**Comment by AlexRuiz7** [comment]
### Failing Cypress tests

I downloaded and checked the logs for the action run [#4546799396](https://github.com/wazuh/wazuh-dashboard/actions/runs/4546799396/jobs/8015878627?pr=33).

### Summary
![image](https://user-images.githubusercontent.com/15186973/228634570-ffb1acbe-f6c9-4a24-a209-6e15e61e1629.png)


### Details
 - core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/basic.spec.js

    >   1) Visualization Builder Base Tests
    >        Create new basic metric visualization:
    >      CypressError: Timed out retrying after 60000ms: `cy.trigger()` failed because this element:
    > 
    > `<button data-test-subj="field-undefined-showDetails" class="osd-resetFocusState osdFieldButton__button">...</button>`
    > 
    > is being covered by another element:
    > 
    > `<div class="euiOverlayMask euiOverlayMask--aboveHeader">...</div>`
    > 
    > Fix this problem, or use {force: true} to disable error checking.
    > https://on.cypress.io/element-cannot-be-interacted-with
    >
    >   2) Visualization Builder Base Tests
    >        Be able to add/ edit and remove a field:
    >      CypressError: Timed out retrying after 60050ms: `cy.click()` failed because this element:
    > 
    > `<button class="euiSuperDatePicker__prettyFormat" data-test-subj="superDatePickerShowDatesButton">...</button>`
    > 
    > is being covered by another element:
    > 
    > `<div class="euiOverlayMask euiOverlayMask--aboveHeader">...</div>`
    > 
    > Fix this problem, or use {force: true} to disable error checking.
    > 
    > https://on.cypress.io/element-cannot-be-interacted-with
    
- core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/dashboard.spec.js

    >   1) Visualization Builder Dashboard Tests
    >        Should be able to create a visualization:
    >      CypressError: Timed out retrying after 60000ms: `cy.trigger()` failed because this element:
    > 
    > `<button data-test-subj="field-age-showDetails" class="osd-resetFocusState osdFieldButton__button">...</button>`
    > 
    > is being covered by another element:
    > 
    > `<div class="euiOverlayMask euiOverlayMask--aboveHeader">...</div>`
    > 
    > Fix this problem, or use {force: true} to disable error checking.
    > 
    > https://on.cypress.io/element-cannot-be-interacted-with
    >
    > 2) Visualization Builder Dashboard Tests
    >      Should be able to edit a visualization:
    >    AssertionError: Timed out retrying after 60000ms: Expected to find element: `[data-test-subj="dashboardEditMode"]`, but never found it.
    >     at Context.eval (http://localhost:5601/__cypress/tests?p=cypress/support/index.js:386:13)

- core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/area.spec.js

    >   1) Vis Builder: Area Chart
    >        Basic test:
    >      CypressError: Timed out retrying after 60000ms: `cy.trigger()` failed because this element:
    > 
    > `<button data-test-subj="field-salary-showDetails" class="osd-resetFocusState osdFieldButton__button">...</button>`
    > 
    > is being covered by another element:
    > 
    > `<div class="euiOverlayMask euiOverlayMask--aboveHeader">...</div>`
    > 
    > Fix this problem, or use {force: true} to disable error checking.
    > 
    > https://on.cypress.io/element-cannot-be-interacted-with

- core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/bar.spec.js

    >   1) Vis Builder: Bar Chart
    >        Basic test:
    >      CypressError: Timed out retrying after 60000ms: `cy.trigger()` failed because this element:
    > 
    > `<button data-test-subj="field-salary-showDetails" class="osd-resetFocusState osdFieldButton__button">...</button>`
    > 
    > is being covered by another element:
    > 
    > `<div class="euiOverlayMask euiOverlayMask--aboveHeader">...</div>`
    > 
    > Fix this problem, or use {force: true} to disable error checking.
    > 
    > https://on.cypress.io/element-cannot-be-interacted-with

- core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/line.spec.js

    >   1) Vis Builder: Line Chart
    >        Basic test:
    >      CypressError: Timed out retrying after 60000ms: `cy.trigger()` failed because this element:
    > 
    > `<button data-test-subj="field-salary-showDetails" class="osd-resetFocusState osdFieldButton__button">...</button>`
    > 
    > is being covered by another element:
    > 
    > `<div class="euiOverlayMask euiOverlayMask--aboveHeader">...</div>`
    > 
    > Fix this problem, or use {force: true} to disable error checking.
    > 
    > https://on.cypress.io/element-cannot-be-interacted-with

- core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/metric.spec.js

    >    1) Vis Builder: Metric Chart
    >         Basic test:
    >       CypressError: Timed out retrying after 60000ms: `cy.trigger()` failed because this element:
    >  
    >  `<button data-test-subj="field-undefined-showDetails" class="osd-resetFocusState osdFieldButton__button">...</button>`
    >  
    >  is being covered by another element:
    >  
    >  `<div class="euiOverlayMask euiOverlayMask--aboveHeader">...</div>`
    >  
    >  Fix this problem, or use {force: true} to disable error checking.
    >  
    >  https://on.cypress.io/element-cannot-be-interacted-with

- core-opensearch-dashboards/opensearch-dashboards/apps/vis_builder/vis_types/table.spec.js

    >   1) Vis Builder: Table Chart
    >        Basic test:
    >      CypressError: Timed out retrying after 60000ms: `cy.trigger()` failed because this element:
    >
    > `<button data-test-subj="field-undefined-showDetails" class="osd-resetFocusState osdFieldButton__button">...</button>`
    >
    > is being covered by another element:
    >
    > `<div class="euiOverlayMask euiOverlayMask--aboveHeader">...</div>`
    >
    > Fix this problem, or use {force: true} to disable error checking.
    >
    > https://on.cypress.io/element-cannot-be-interacted-with

- core-opensearch-dashboards/opensearch-dashboards/dashboard_sanity_test_spec.js (7/34)

    > 1) dashboard sample data validation
    >      checking home page
    >        checking tutorial_directory display:
    >    AssertionError: Timed out retrying after 60000ms: Expected to find element: `a[href="/app/home#/tutorial_directory"]`, but never found it.
    >
    > 2) dashboard sample data validation
    >      adding sample data
    >        "before all" hook for "checking ecommerce dashboards displayed":
    >    AssertionError: Timed out retrying after 60000ms: Expected to find element: `button[data-test-subj="addSampleDataSetecommerce"]`, but never found it.
    >
    > 3) dashboard sample data validation
    >      adding sample data
    >        "after all" hook for "checking ecommerce dashboards displayed":
    >    CypressError: You attempted to make a chai-jQuery assertion on an object that is neither a DOM object or a jQuery object.
    >
    > 4) dashboard sample data validation
    >      checking Dev Tools
    >        checking welcome panel display:
    >    AssertionError: Timed out retrying after 60000ms: Expected to find element: `div[data-test-subj="welcomePanel"]`, but never found it.
    >
    > 5) dashboard sample data validation
    >      checking Dev Tools
    >        checking dismiss button display:
    >    AssertionError: Timed out retrying after 60000ms: Expected to find element: `button[data-test-subj="help-close-button"]`, but never found it.
    >
    > 6) dashboard sample data validation
    >      checking Dev Tools
    >        checking console input area display:
    >    AssertionError: Timed out retrying after 60000ms: Expected to find element: `div[data-test-subj="request-editor"]`, but never found it.
    >
    > 7) dashboard sample data validation
    >      checking Dev Tools
    >        checking console output area display:
    >    AssertionError: Timed out retrying after 60000ms: Expected to find element: `div[data-test-subj="response-editor"]`, but never found it.

**Comment by yenienserrano** [comment]
Was not taking the correct branch from the cypress repository that's why some tests were failing.
With the change of the workflow they still do not pass the sample data tests.
I'm still looking to see if I can omit those tests as we modify that part and they will fail every time.

![image](https://user-images.githubusercontent.com/63758389/231788873-04b20c91-7072-4f48-b117-ea43ec75692c.png)
