### ISSUE TITLE
Support new stage RC 1 for 4.9.2 in wazuh-dashboard repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-dashboard#381]
## Description

This issue attempts to support a new stage RC 1 for 4.9.2 in the wazuh-dashboard repository.

## Tasks

- [x] Ensure changelog is updated for 4.9.2 (if applicable).
- [x] Bump revision for branch 4.9.2 on wazuh-dashboard repository. https://github.com/wazuh/wazuh-dashboard/pull/382
- [x] Create tag v4.9.2-rc1 from branch 4.9.2 on wazuh-dashboard repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard/releases/tag/v4.9.2-rc1.
