### ISSUE TITLE
Support new stage Beta 1 for 4.10.0 in wazuh-dashboard repository

### ISSUE THREAD

**Issue by wazuhci** [wazuh/wazuh-dashboard#425]
## Description

This issue attempts to support a new stage Beta 1 for 4.10.0 in the wazuh-dashboard repository.

## Tasks

- [x] Ensure changelog is updated for 4.10.0 (if applicable).
- [x] Bump revision for branch 4.10.0 on wazuh-dashboard repository.
- [x] Create tag v4.10.0-beta1 from branch 4.10.0 on wazuh-dashboard repository.
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-dashboard/releases/tag/v4.10.0-beta1.

**Comment by asteriscos** [comment]
LGTM :heavy_check_mark:
