### ISSUE TITLE
Global menu

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard#83]
## Introduction

This UX redesign tier 1 scope involves mostly a new general menu for the whole interface. 

Now that we have control over the complete dashboard, we want to improve the user experience, making it easier to access Wazuh features. Our first step will be to create a new menu experience in line with what the platform is designed to work with: the left navigation drawer.

Our current menu is embedded into our main application in the top bar:

![image](https://github.com/wazuh/wazuh-dashboard/assets/2181918/eaf6b710-1124-4c3d-9684-4cb11e5d820e)

We want to incorporate this accesses into the global navigation drawer, transforming the current look (on the left) to something like:

![image](https://github.com/wazuh/wazuh-dashboard/assets/2181918/22fd3b81-5cc7-4be7-ae40-4d41845f5ac7)

Of these, we want to pursue the 1st one, as it allows us to implement the global navigation drawer in a simple and fast pace manner, and allows us to evolve the main plugin with time, iteratively, instead of a big bang devel approach, unlike option 2 and 3.

It is important that we leverage the built-in styles and looks so that our menu can evolve with the new upstream changes which are on their way (for example https://github.com/opensearch-project/OpenSearch-Dashboards/issues/4298).

We must customize the icons for each category. The UI library provides a set of icons we could use.

It's also important to study what would happen in the case of newer applications arriving from upstream that use the same categories as we propose here.

## Functional requirements

- Users must be able to navigate to the main page of each module by accessing it using the global navigation drawer.

## Non-functional requirements

- The health-check must not run on every navigation through the navigation drawer. It sould only run when neccesary.
- Background requests and state sharing must be kept at a minimum.
- We must use the i18n framework, allowing future translation.
- We must use the accessibility options built in the platform.
- We must support dark and light themes.
- We must support testing with Cypress or other UI testing frameworks (use identifiable selectors, etc.)

## Plan

- [x] #93
- [ ] #94
- [ ] Update the documentation after the new menu

**Comment by Desvelao** [comment]
# Research
> Investigate: menu as a standalone plugin

The platform menu displays all the registered and visible applications. A plugin can register any number of applications in the platform menu. The app registration needs to define what will be rendered when the user access to the menu.

This means that if we do a plugin to register all the applications, then it must have access to the render methods of them. The rendering method can come from other plugins or itself. If they come from other plugins, this creates more dependency between these plugins.

The menu as a standalone plugin can need more logic than if each plugin manages the application registration.

I think that @asteriscos was working in a POC to register multiple applications. It would be interesting to know what approach followed.

**Comment by Desvelao** [comment]
# Research

The current plugin is a monolith and this can generate multiple problems if we want to decouple into different applications if this architecture is kept as mentioned ones:

- The health check page
- The angular routing problem
- The embedded discover urls

## Health check page

This is a page that does some checks and creates or updates some elements that are needed to work the plugin.

Each route of the current plugin can do some checks. If some of them fail, then a redirection to the health check page will be done. This means we should decide how to accommodate the health check in the different applications. It could be a different application or a route in each future application if we want to keep the current logic.

## The angular routing problem

I am not sure what it is referring to.

The current plugin uses as base AngularJS, despite part of the application being migrated to ReactJS. The routing is done with AngularJS.

## The embedded discover urls

The `Events` tab of each module uses the URL to set the filters.

**Comment by Desvelao** [comment]
# Research

Considerations:

- Disable plugins by role: `disabled_roles` setting in `wazuh.yml`
- Disable plugin visibility (on adding new host): `extensions.*` in `wazuh.yml`
- Disable plugin visibility by host: in `Settings > Modules`
- Disable plugin visibility by selected agent compatibility.

**Comment by Desvelao** [comment]
# Research

@asteriscos and me was researching how to create the applications in the side menu and clicking on them redirects to them.

## Possible approach: redirect to the monolithic plugin

Register each application so it appears in the side menu and is accessible. Then, the `mount` method should redirect to the hidden monolitic plugin.

```ts
core.application.register({
          id,
          title,
          icon: core.http.basePath.prepend(
            logosInitialState?.logos?.[SIDEBAR_LOGO]
              ? getAssetURL(logosInitialState?.logos?.[SIDEBAR_LOGO])
              : getThemeAssetURL('icon.svg', UI_THEME),
          ),
          mount: async (params: AppMountParameters) => {
            window.location.href = href;
          },
          category,
        });
```

**Comment by Desvelao** [comment]
# Possible approach: generate the application routes according to the selected application

This approach generates the routes of each application dynamically. The default route is changed to the current route that should be visible.

Pros:
- Resolve the problem of the store being recreated when changing of Wazuh application.

Cons:
- Add technical debt to the base application router.

## Implementation

Change the routes dynamically:

```
// public/services/routes.ts
const redirectTo: getApplicationRedirectTo()
// router definition
.when('/', {
      redirectTo,
      outerAngularWrapperRoute: true,
    })
    .when('', {
      redirectTo,
      outerAngularWrapperRoute: true,
    })
    .otherwise({
      redirectTo,
      outerAngularWrapperRoute: true,
    });
```

getRootRedirectTo is a getter. Use a setter when the application is mounted in the `mount` method:
```ts
// public/plugin.ts
mount: (params){
  setWzMainParams(redirectToRoot);
  // rest of logic
}
```

Create the getter/setter:
```ts
// public/kibana_services.js
export const [getApplicationRedirectTo, setApplicationRedirectTo] =
  createGetterSetter<any>('WzApplicationRedirectTo');
```

**Comment by Desvelao** [comment]
# Design

Following the approach: https://github.com/wazuh/wazuh-dashboard/issues/83#issuecomment-1683978025

# Steps

- [ ] Register the proposed applications
- [ ] Rename built-in platform categories
- [ ] Explore the redirections
- [ ] Replace references to `/app/wazuh` to `/app/{currentAplication}`. Suggestion: research to use some services provided by the plugin.
- [ ] Share state between applications
  - [ ] Selected agent
  
# Discussions

- [ ] What to do with global breadcrumb?
- [ ] API hosts and valid index patterns are updated when opening or closing the current menu. Should it behavior keep and how?
- [ ] Visibility of applications related to the current modules that depend on API host configuration, and selected agent. Should it be supported? How should we implement it?

**Comment by Desvelao** [comment]
## Adapt the redirections

| Old URL | New URL | Affected files |
| --- | --- | --- |
| /app/wazuh#/settings | /app/wz-server-api | plugins/main/public/components/health-check/container/health-check.container.tsx |

**Comment by yenienserrano** [comment]
When you want to navigate between the Endpoint security, Thread intelligence, Security operations and Cloud security modules and go through the heath check instead of redirecting to the desired view, it redirects to the overview.

On the other hand, changing views is changing the plugin, as the url changes and the application takes longer to load the views, so it slows down the application and in my environment it doesn't have much data to load.

**Comment by Desvelao** [comment]
# Meeting

## Discussions

- What to do with global breadcrumb?
- API hosts and valid index patterns are updated when opening or closing the current menu. Should it behavior keep and how?
- Visibility of applications related to the current modules that depend on API host configuration, and selected agent. Should it be supported? How should we implement it?
- Name of the platform categories
- Menu for agent
![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/38d0201e-7a55-4461-aa34-09a93a41f3f9)
- Should the tabs related to other applications be removed?
  - current section: Settings  
  ![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/b9f8d69e-0fcd-4501-a441-9c52ebffcbad)
  - current section: Tools  
  ![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/532054ab-0ac2-4c56-bdfb-eb37417114e4)
- https://github.com/wazuh/wazuh-dashboard/issues/83#issuecomment-1689944098
- When the user accesses an application, get a new API token. This means if the user is changing between applications, he/she will get new tokens.

**Comment by Desvelao** [comment]
# Changes

- Create new applications in the side menu:

| Category | Name | Section in monolith plugin |
| --- | --- | --- |
| Management | Modules | Settings > Modules |
| Management | Miscellaneus | Settings > Miscellaneus |

> Notes:
> Settings > Miscellaneus should be moved to Configuration
> Modules app only contains the visibility of some applications. This should be refactored to support all the applications.

**Comment by JuanGarriuz** [comment]
### Server Management Issues

> Groups

When we click on the eye icon to navigate to Agent-preview, we go to /app/wz-groups#/agents?_g=(filters, using monolithic logic. The function that works over the eye button is showAgent() which works like: 

![image](https://github.com/wazuh/wazuh-dashboard/assets/124377319/efcaeca4-c5eb-45a0-a339-67eaeddea510)

![image](https://github.com/wazuh/wazuh-dashboard/assets/124377319/1de76600-539f-45e9-8c68-5c71211d7c65)

The expected result is to navigate to the Endpoints summary:

![image](https://github.com/wazuh/wazuh-dashboard/assets/124377319/2a5af5d7-34e9-4f9d-a8a4-538ecbd4eff3)

But keep into Groups

![image](https://github.com/wazuh/wazuh-dashboard/assets/124377319/4ebcf18c-0407-4481-a2ad-d40d04421a5c)


We can find that code in => plugins/main/public/controllers/management/groups.js
That code modified the URL before "#" to navigate a new web section, but it doesn't work in the new menu bar logic, because we navigate across the menu bar. 

To fix it there are 2 main branches; create a new function that works in all redirection code lines, or change old logic code lines with a href. 

> Statitics

When we click on the settings button, we go to/app/wz-statistics#/settings?tab=configuration&category=statistics, using monolithic logic. The function that works over the button is navigateToModule() which works like: 

![image](https://github.com/wazuh/wazuh-dashboard/assets/124377319/e18e8af3-8d30-4898-8b84-8a8bdbeeb289)

![image](https://github.com/wazuh/wazuh-dashboard/assets/124377319/b35750b5-85e8-41d2-80bf-567d572a5fbb)

The expected result is to navigate to Configuration:

![image](https://github.com/wazuh/wazuh-dashboard/assets/124377319/c808e75a-5fb8-42b0-8853-062cf32e84f1)

But keep in Statistics

![image](https://github.com/wazuh/wazuh-dashboard/assets/124377319/e18e8af3-8d30-4898-8b84-8a8bdbeeb289)


We can find that code in => plugins/main/public/controllers/management/components/management/statistics/statistics-overview.js
That code modified the URL before "#" to navigate a new web section, but it doesn't work in the new menu bar logic, because we navigate across the menu bar. 

To fix it there are 2 main branches; create a new function that works in all redirection code lines, or change old logic code lines with a href. 

>Monitoring

When we click on the Agents button, we go to /app/wz-cluster#/agents-preview/?_g=(filters:, using monolithic logic. The function that works over the button is a href. 

The expected result is to navigate to Configuration:

![image](https://github.com/wazuh/wazuh-dashboard/assets/124377319/58234c9f-5432-4362-be06-cb6be2343fb7)

But keep in Statistics

![image](https://github.com/wazuh/wazuh-dashboard/assets/124377319/f73a1be6-0d21-49fe-8ef3-e93d7eaae26e)


We can find that code in => plugins/main/public/controllers/management/monitoring.js
That code modified the URL with a href. but that means that there are at least 3 different ways to navigate over the different parts of the app. 

To fix it there are 2 main branches; create a new function that works in all redirection code lines, or change old logic code lines on the href. 

>Conclusion

If we fix those changes all navigates code lines to hrefs the code will be too much dirt, making it more difficult to fix bugs in the future, and making the code less reusable. 
Conversely, it means that we have to take more time to make reusable and cleaner code.

**Comment by yenienserrano** [comment]
> Research the impact of: API hosts and valid index patterns are updated when opening or closing the current menu. Should it behavior keep and how?

Requests are made to update the index pattern and apis selectors. 
This is not very reliable because if the user adds an index pattern or a new api and opens the selector, he will not see the changes until he opens the menu or refreshes the page.
With the index pattern it would only affect if you have more than 1 window open with Wazuh, because if the user only handles 1 window when adding an index pattern and then navigates to another view, the requests would be executed when mounting the component.
For me, it is better to add to the documentation that after adding a new api or index pattern you have to restart the browser, and save us from making those requests every so often or when the user makes a specific action.

**Comment by Desvelao** [comment]
# Changes

- Create new applications in the side menu:

| Category | Name | Section in monolith plugin |
| --- | --- | --- |
| Endpoint security | Overview | Modules directory |

**Comment by Desvelao** [comment]
# Meeting

## Discussions:
- https://github.com/wazuh/wazuh-dashboard/issues/83#issuecomment-1693052343
> We can also use the onMouseEnter function to execute the request when the user puts the mouse over the selector, but this may cause unnecessary requests.

**Comment by Desvelao** [comment]
# Meeting

Current status:

- Problems
  - Share state
    - Redux store and singleton are reset when changing applications due to a page refresh when the application is mounted
    - Loop in the health check
    - When you change application quickly, sometimes it gives you an error in the console and shows you the previous view to the currently selected one.
    - Sometimes when you want to enter to some module it always redirects you to the Endpoints summary. Modules - Endpoints summary
    - Problems with the tabView in the url, in the views you should change the value but then returns to the previous value.
  - Redirections to applications

- Comment
  - Applications visibility:
    - configuration
    - seleted API host
    - selected Agent (affecting to old modules)
  - UX problems:
    - Too many applications
    - Switching applition is slow

**Comment by Desvelao** [comment]
Requirements update

```
| Category | Name | ID | Section in monolith plugin |
|---------------------|-----------------------------------|---|---------------------------------------------|

| Home | Overview | wz-home | Modules directory | This is the home (the home icon)

| Endpoint security | Security Configuration Assessment | security-configuration-assessment | Modules > Security Configuration Assessment | RENAME Configuration assesment
| Endpoint security | Policy monitoring | policy-monitoring | Modules > Policy monitoring | RENAME to Malware detection  (this is rootcheck now)
| Endpoint security | Integrity monitoring | integrity-monitoring | Modules > Integrity monitoring | RENAME to File integrity monitoring

| Endpoint security | System auditing | system-auditing | Modules > System auditing | DELETE
| Endpoint security | OpenSCAP | openscap | Modules > OpenSCAP | DELETE
| Endpoint security | CIS-CAT | ciscat | Modules > CIS-CAT | DELETE

| Threat intelligence | Security events | security-events | Modules > Security events | RENAME Threat hunting
| Threat intelligence | Vulnerabilities | vulnerabilities | Modules > Vulnerabilities | RENAME to Vulnerability detection
| Threat intelligence | MITRE ATT&CK | mitre-attack | Modules > MITRE ATT&CK | 
| Threat intelligence | Virustotal | virustotal | Modules > Virustotal |

| Security operations | PCI DSS | pci-dss | Modules > PCI DSS |
| Security operations | GDPR | gdpr | Modules > GDPR |
| Security operations | HIPAA | hipaa | Modules > HIPAA |
| Security operations | NIST 800-53 | nist-800-53 | Modules > NIST 800-53 |
| Security operations | TSC | tsc | Modules > TSC |
| Security operations | IT Hygiene | it-hygiene | Agents > {agent_id} -> Inventory | 

| Security operations | Osquery | osquery | Modules > Osquery | DELETE

| Cloud security | AWS | amazon-web-services | Modules > AWS |
| Cloud security | Google Cloud | google-cloud | Modules > Google Cloud |
| Cloud security | GitHub | github | Modules > GitHub |
| Cloud security | Office365 | office365 | Modules > Office365 |
| Cloud security | Docker listener | docker-listener | Modules > Docker listener | RENAME to Docker


| Explore | Discover | - | - | Renamed from "Openseach dashboards"
| Explore | Dashboards | -| - |
| Explore | Visualize | - | - |
| Explore | Reporting | - | Comes from "Opensearch plugins" 
| Explore | Alerting | - |
| Explore | Maps | - |
| Explore | Notifications | - |


| Server management | Endpoints summary | endpoints-summary | Agents | This comes from Endpoint security
| Server management | Groups | groups | Management > Groups | RENAME to Endpoint groups
| Server management | Rules | rules | Management > Rules |
| Server management | Decoders | decoders | Management > Decoders |
| Server management | CDB lists | cdb-lists | Management > CDB lists |
| Server management | Status | server-status | Management > Status |
| Server management | Cluster | cluster | Management > Cluster |
| Server management | Statistics | statistics | Management > Statistics |
| Server management | Logs | logs | Management > Logs |
| Server management | Settings | settings | Management > Configuration |
| Server management | API console | api-console | Tools > API console | RENAME Dev tools
| Server management | Ruleset test | ruleset-test | Tools > Ruleset test |
| Server management | RBAC | rbac | Security | RENAME to Security


| Indexer/dashboard Management | Reporting | reporting | Management > Reporting | Comes from "server management" | REMOVE and use Explore reporting highjacking the download capability of the standard plugin
| Indexer/dashboard Management | Server API | server-api | Settings > API configuration |
| Indexer/dashboard Management | Modules | modules | Settings > Modules | DELETE
| Indexer/dashboard Management | Server data | server-data | Settings > Sample data |
| Indexer/dashboard Management | Configuration | configuration | Settings > Configuration | RENAME to Wazuh plugin settings
| Indexer/dashboard Management | Logs | app-logs | Settings > Logs | RENAME to Wazuh plugin logs
| Indexer/dashboard Management | About | about | Settings > About | RENAME to Wazuh plugin about
| Indexer/dashboard Management | Dev tools | - | - | Comes from management
| Indexer/dashboard Management | Stack management | - | - | Comes from management

| Indexer/dashboard Management | Security | - | -> Comes from Opensearch plugins, nice to have move it to indexer./dashaboard management 
| Indexer/dashboard Management| Index management | - |
| Indexer/dashboard Management | Snapshot management | - |

```
