### ISSUE TITLE
Update check service UI

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-dashboard#84]
## Introduction

We want to inform our users a new version of Wazuh is available from the `wazuh-dashboard` UI.

- A user must be able to dismiss a notification, so it won't appear again
- A user must be able to disable the check for updates, so no check is made at all from the global configuration section
- A user must be able to see with details about new version, clicking in the notification or navigating to the `About` menu

The Wazuh API will implement the necessary endpoints for the dashboard to get the relevant information.

## Design

We can implement the notification logic by:
- checking for updates on each log-in
- checking for updates at a given period (from dashboard to the API)
- checking for updates by clicking a button in the About page

We might implement them all at some point, but we need to evaluate the impact on the user workflow to ensure the feature is usable and don't get in the way.

We can design this feature as a new plugin for `wazuh-dashboards`, and render its contents inside the main plugin under the About page.

## Plan

- [x] https://github.com/wazuh/wazuh-dashboard/issues/87
- [x] https://github.com/wazuh/wazuh-dashboard/issues/88
- [x] https://github.com/wazuh/wazuh-dashboard/issues/97
- [x] https://github.com/wazuh/wazuh-dashboard/issues/105
- [x] https://github.com/wazuh/wazuh-dashboard/issues/106
- [x] https://github.com/wazuh/wazuh-dashboard/issues/109
- [x] https://github.com/wazuh/wazuh-dashboard/issues/114
- [ ] https://github.com/wazuh/wazuh-dashboard/issues/111
- [x] https://github.com/wazuh/wazuh-dashboard/issues/96
- [x] https://github.com/wazuh/wazuh-documentation/issues/6677
