### ISSUE TITLE
Create new plugin wazuh-check-updates

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard#87]
|Part of Epic|
|---|
|#84|
## Description
We need to develop a **new plugin** responsible for querying an external service to **retrieve information about the latest available updates** along with their corresponding features. This dedicated plugin will then be utilized by the primary Wazuh plugin, enabling it to notify users whenever new updates become accessible.
The plugin will also have a **component to notify the user when there is a new updates**, a **component to view the deployment status**, a **component to view the details** and a **component to allow the user to change their notification preferences**. This component will be used by the main plugin.
What we are looking for with the new plugin is to have the functionality referred to the notification of new updates modularized.

## Tasks
- [x] **[Backend]** Expose an endpoint to query the new updates and their details. The endpoint should consult an external service about new updates and their details. **Initially the response from the external service will be mocked**
- [x] **[Backend]** Expose an endpoint to query user preferences.
- [x] **[Backend]** Expose an endpoint to update user preferences.
- [x] **[Backend]** Manage saved objects to save settings and user configurations.
- [x] **[Backend]** Run a cron job to periodically check for available updates.
- [x] **[Frontend]** Expose a component to notify the user of new updates so that it can be consumed by other plugins.
  - It must have a dismiss button to dismiss all further notifications about the presented version.
  - It must have an option to reject all future notifications of new updates.
  - It must contain a dynamic link so that the user can go to a page and see the  details of the update.
- [x] **[Frontend]** Expose a component to show the deployment status and a button to check available updates.
- [x] **[Frontend]** Expose a component to show the details of the current available update.
- [x] **[Frontend]** Expose a component to allow the user to change their notification preferences.
- [x] **[Frontend]** It must use i18n.
- [x] Unit tests for each development

## Notification mockup
![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/d08c5a80-32b2-40ad-85e2-8e90272fb9c8)

- **New update message:** A text that indicates that there is a new release available. E.g.: **¡Wazuh 4.8.0 is available!**
- **Link to release notes:** When the user clicks the link, it should open a new tab with the release notes official page.
- **Dismiss future updates check:** An option check to give the user the possibility to avoid seeing these types of notifications in the future. E.g.: **I don't want to know about future releases**. If the option is checked, when the user closes the notification throw the button the configuration will be saved.
- **Close button:** A button to close the notification. When the user clicks on it, it must be saved so that the notification of this release no longer appears for the user.

## Deployment status mockup
![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/7afbc7e9-bdb6-4399-af25-2d02d6ffad6a)

- **Deployment status:** Shows if is up to date or if there are available updates.
- **Tooltip:** Shows when the last time new updates were checked.
- **Check updates button:** A button to check available updates.

## Current update mockup
![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/4f18f8ef-3e0d-4261-abc4-1cdf35d59065)

- **New update message:** A text that indicates that there is a new release available. E.g.: **¡Wazuh 4.8.0 is available!**
- **Link to release notes:** When the user clicks the link, it should open a new tab with the release notes official page.
- **Link to upgrade guide:** When the user clicks the link, it should open a new tab with the upgrade guide official page.
- **Show detail accordion:** A section where user can expand and view the update description.

## User preference mockup
![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/f8f62b63-19bb-4678-816e-cfb843b97095)

- **Dismiss future updates check:** An option check to give the user the possibility to avoid seeing these types of notifications.
