### ISSUE TITLE
Integrate wazuh-check-updates plugin and update the About page

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard#88]
|Part of Epic|
|---|
|#84|
## Description
Integrate  the wazuh-check-updates plugin developed in issue https://github.com/wazuh/wazuh-dashboard/issues/87 with the main plugin.
This integration will allow us to consume the components exposed by the wazuh-check-updates plugin.
The "About" page should show whether the current version is up to date or not. If it is not up to date, it should show the latest available version and should give the user the ability to see the details in the release notes for each release.

## Tasks
- [x] Integrate wazuh-check-updates plugin
- [x] Replace the Angular template for a React component
- [x] Consume the UpToDateStatus component from wazuh-check-updates plugin
- [x] Consume the CurrentUpdateDetails component from wazuh-check-updates plugin
- [x] Consume the DismissNotificationCheck component from wazuh-check-updates plugin
- [x] Unit tests

### Up to date
![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/e84848a8-6b80-440f-954f-5b9b2b53dbba)

### New release available
![image](https://github.com/wazuh/wazuh-dashboard/assets/103193307/b8e1ac17-2e66-4e5f-8129-f0d1b3624f8b)
