### ISSUE TITLE
Integrate our menu into the platform global navigation drawer

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-dashboard#94]
## Description

In this issue, we'll track the progress to implement the selected design (see wazuh/wazuh-dashboard#93) to integrate Wazuh's app menu into the platform's navigation drawer menu.

### Design

See selected design in:

- wazuh/wazuh-dashboard#93 

### Requirements

See requirements in:
- wazuh/wazuh-dashboard#83 

### Tasks

- [x] wazuh/wazuh-kibana-app#5841
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5820

----

- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5826
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5849
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5814
- [x] Research the impact of API hosts and valid index patterns that are updated when opening or closing the current menu. Should it behavior keep and how? https://github.com/wazuh/wazuh-dashboard/issues/83#issuecomment-1693052343
- [ ] https://github.com/wazuh/wazuh-kibana-app/issues/5965
- [x] https://github.com/wazuh/wazuh-dashboard/issues/92
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5835
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5848
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5893
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5900
- [x] https://github.com/wazuh/wazuh-kibana-app/issues/5964
- [x] Manage selected agent on IT Hygiene application https://github.com/wazuh/wazuh-dashboard-plugins/pull/6005
- [x] https://github.com/wazuh/wazuh-dashboard-plugins/pull/6086
- [x] https://github.com/wazuh/wazuh-packages/pull/2578

**Comment by Desvelao** [comment]
Branching strategy

![image](https://github.com/wazuh/wazuh-dashboard/assets/34042064/a241622f-7dcc-4ed6-a694-f9702e61c044)

**Comment by yenienserrano** [comment]
With the new OSD 2.10.0 update the breadcrumb has been updated and needs to be updated.

![image](https://github.com/wazuh/wazuh-dashboard/assets/63758389/6d86ef48-9097-4958-bbdd-7982822f5e0e)

**Comment by yenienserrano** [comment]
We need to fix the redirection of an agent to some group as it has to redirect to the groups plugin and is trying to go to endpoint-group.

https://github.com/wazuh/wazuh-kibana-app/blob/feat/83-move-menu-items-to-applications/plugins/main/public/components/common/util/agent-group-truncate/group-truncate.tsx#L55

https://github.com/wazuh/wazuh-kibana-app/blob/feat/83-move-menu-items-to-applications/plugins/main/public/controllers/management/components/management/configuration/configuration-switch.js#L214

<details><summary>Details</summary>
<p>

![image](https://github.com/wazuh/wazuh-dashboard/assets/63758389/0fda6d57-2355-4e76-b3c5-0851ffacb95a)
![image](https://github.com/wazuh/wazuh-dashboard/assets/63758389/1f8a8ff5-b272-4805-a8dc-52a0542b5739)
![image](https://github.com/wazuh/wazuh-dashboard/assets/63758389/dbeefebd-ed01-4776-bb10-5e367d31f572)

</p>
</details>
