### ISSUE TITLE
Fix desing implementation

### ISSUE THREAD

**Issue by lucianogorza** [wazuh/wazuh-dashboard#96]
|Part of Epic|
|---|
|#84|
## Description
Implement the following changes to improve the solution.

## Tasks
- [x] **[Frontend Main Plugin]** In the `About` page delete the API table and leave a React component the same as previous Angular template.
- [x] **[Frontend Check Updates Plugin]** Delete unused components related with About page.
- [x] **[Frontend Check Updates Plugin]** In the `UpdatesNotification` component only ask for available updates if user doesn't check "Disable update notifications".
- [x] **[Frontend Main Plugin]** In API Table handle check updates button errors and show toast.
- [x] **[Frontend Main Plugin]** In API Table show tooltip with the error message when status is "error".
- [x] **[Frontend Main Plugin]** Unit tests for new Flyout with updates details.
- [x] **[Docker]** Update WZ_HOME in README file.
